import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next and must not be edited; it carries a
    // triple-slash path reference that the next/typescript rules would reject.
    ignores: [".next/**", "node_modules/**", "next-env.d.ts"],
  },
  {
    // Honor the repo-wide convention of prefixing intentionally-unused bindings
    // (unused fn args, placeholder vars, caught errors) with a leading `_`.
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
];

export default eslintConfig;
